### ISSUE TITLE
Base de datos: 2. Definir los atributos para cada entidad, considerando los datos necesarios para cumplir con las funcionalidades especificadas.

### ISSUE THREAD

**Issue by Maxg8704** [Grupo-Seven-ISPC/ARGBroker-Demo-Grupo-Seven#13]

**Comment by Fabrizio112** [comment]
# Entidades con sus respectivos atributos:

## Usuario:
-usuario_id (_INT_) **PK**
-saldo (_FLOAT_)
-perfil_id (_INT_)  **FK**
-nombre (_STR_)
-apellido (_STR_)
-dni (_INT_)  **PK**
-correo_electronico (_STR_)

## Accion:
-accion_id (_INT_)  **PK**
-nombre (_STR_)
-símbolo (_TEXT_)
-ultimo_operado (_INT_)
-cantidad_compra_diaria (_INT_)
-precio_compra_actual (_INT_)
-precio_venta_actual (_INT_)
-apertura (_INT_)
-minimo_diario (_INT_)
-maximo_diario (_INT_)
-ultimo_cierre (_INT_)

## Operación:
-id_operacion (_INT_) **PK**
-usuario_id (_INT_) **FK**
-accion_id (_INT_)  **FK**
-id_accion_del_usuario (_INT_) **FK**
-monto (_INT_)  _NULLABLE=True_
-cantidad (_INT_)  _NULLABLE=True_
-fecha (_DATE_)
-comisión (_FLOAT_)
-id_estado (_INT_) FK

## Perfil de Inversor: (conservador,medio,agresivo)
-id_perfil (_INT_) **PK**
-nombre_perfil (_STR_)
-descripcion_perfil (_TEXT_)  _NULLABLE=True_

## Accion del Usuario: (compra,venta)
-id_accion_del_usuario (_INT_)  **PK**
-nombre (_STR_)
-descripción (_TEXT_)  _NULLABLE=True_

## Estado de Inversion: (Operado,Pendiente,Cancelada)
-id_estado (_INT_) **PK**
-nombre (_STR_)
