### ISSUE TITLE
Base de datos: 3. Establecer las relaciones entre las entidades identificadas.

### ISSUE THREAD

**Issue by Maxg8704** [Grupo-Seven-ISPC/ARGBroker-Demo-Grupo-Seven#14]

**Comment by Fabrizio112** [comment]
# Relaciones:

1. Usuario **_poseer_** Perfil de Inversor(_N a 1_)
1. Usuario **_poseer_** Acciones (_N a M_)
1. Usuario **_realizar_** Operacion (_1 a N_)
1. Operacion **_incluir/involucrar_** Accion (_N a 1_)
1. Operacion **_incluir/involucrar_** Accion del Usuario (_N a 1_)
1. Operacion **_incluir/involucrar_** Estado de Inversion(_N a 1_)
