### ISSUE TITLE
Etica: 1. Describir cómo el grupo se conforma como instrumento legal (Empresa, Socios, CEO, Empleados) y si tendrán un contrato con que cláusulas.

### ISSUE THREAD

**Issue by Maxg8704** [Grupo-Seven-ISPC/ARGBroker-Demo-Grupo-Seven#18]

**Comment by marialis19** [comment]
1. Conformación Legal de la Empresa:  
- Descripción del Grupo como Instrumento Legal 

     · Tipo de Empresa:  Sociedad Anónima (S.A.) 

     · Socios:  cada miembro del grupo es socio fundador. 

     · CEO:  se designa un CEO ( director ejecutivo) entre los socios. 

     · Empleados: otros roles asignados a los empleados contratados. 

- Contrato social: Cláusulas fundamentales

     · Objeto Social: desarrollo y comercialización de software para transacciones financieras en el Mercado de Valores de Buenos Aires (Merval). 

     · Capital Social: (fondos propios de la empresa) 100,000 dividido en 1,000 acciones de 100 cada una. 

     · Administración: un directorio con Presidente y Vicepresidente. 

     · Distribución de Utilidades: Proporcional a la participación en el capital. 

     · Resolución de Conflictos: conforme al Código penal, Consejo Profesional de Ciencias Informáticas de Córdoba (van todas las leyes dadas en etica?)
