### ISSUE TITLE
Etica: 2. Describir quiénes y ante quien deben matricularse a nivel provincial para ejercer la Profesión.

### ISSUE THREAD

**Issue by Maxg8704** [Grupo-Seven-ISPC/ARGBroker-Demo-Grupo-Seven#19]

**Comment by marialis19** [comment]
2. Matriculación Profesional

- Requisitos y Procedimientos:
     · Quiénes deben matricularse: Todos los desarrolladores de software, profesionales de informática y profesionales asesores involucrados en la empresa. 
     · Dónde matricularse: Consejo Profesional de Ciencias Informáticas de la Provincia de Córdoba (CPCIPC) 7642/87.
     · Requisitos: Título habilitante, inscripción y pago de la matrícula correspondiente. (https://www.argentina.gob.ar/servicio/registrar-un-software-puesto-en-conocimiento-publico#:~:text=Este%20tr%C3%A1mite%20te%20permite%20registrar%20ante%20la%20Direcci%C3%B3n,o%20titulares%20de%20software%20o%20quienes%20ellos%20designen.) (modificar en caso de que quieran agregar algo, sino borrar no mas)

**Comment by AnaCamilaAlmiron** [comment]
Para la correcta matriculación, deben hacerlo todos los desarrolladores de Software, profesionales de informática y profesionales asesores involucrados en la empresa, este tramite debe hacerse en el Consejo Profesional de Ciencias Informática de la Provincia de Córdoba (CPCIPC) 7642/87. Para ellos deben poseer el titulo habilitante, una inscripción y el pago de la matricula correspondiente.
