### ISSUE TITLE
Etica: 3. Describir que requerimientos deben cumplir el código programado y las bases de datos según la legislación vigente

### ISSUE THREAD

**Issue by Maxg8704** [Grupo-Seven-ISPC/ARGBroker-Demo-Grupo-Seven#20]

**Comment by marialis19** [comment]
3. Requerimientos Legales del Código y Bases de Datos

- Leyes aplicables:
     · Ley 25.326 de Protección de Datos Personales: seguridad y privacidad de los datos. 

     ·Ley 11.723 de Propiedad Intelectual: derechos de autor del software. 

     · Ley 26.388 de Delitos Informáticos: protección contra acceso no autorizado. 

     · Ley 25.236 de Firma Digital: autenticidad e integridad de transacciones. 

(enriquecer con artículos específicos)
