### ISSUE TITLE
Etica: 4. Enumerar los pasos para que ARGBroker sea parte del Registro Nacional de software.

### ISSUE THREAD

**Issue by Maxg8704** [Grupo-Seven-ISPC/ARGBroker-Demo-Grupo-Seven#21]

**Comment by marialis19** [comment]
4. Registro Nacional de Software

- Pasos para registrar la Aplicación: 
     · Recolección de Documentación: Recopilar toda la documentación técnica y legal del software.
     · Presentación en la Agencia Nacional de Promoción Científica y Tecnológica: Completar y presentar los formularios requeridos.
     · Pago de Aranceles: abonar costos asociados al registro.
     · Obtención de Certificado: Recibir la certificación que acredita el registro.
(corregir si está mal)
