### ISSUE TITLE
Etica: 6. Si el código es replicado, describir como la Ley de Propiedad Intelectual puede salvaguardar a ARGBroker.

### ISSUE THREAD

**Issue by Maxg8704** [Grupo-Seven-ISPC/ARGBroker-Demo-Grupo-Seven#23]

**Comment by marialis19** [comment]
6. Protección de la Propiedad Intelectual

- Replicación del Código: 

    · Ley 11.723: Protección de derechos de autor, incluyendo la posibilidad de iniciar acciones legales por infracción de derechos de propiedad intelectual. (Artículos 1-2-3-4-5 expandir info)

**Comment by luchogigena** [comment]
_**-¿ Cómo puede la ley de propiedad intelectual salvaguardar a ARGBroker si el código es replicado?**_ 

 
La Ley de Propiedad Intelectual de Argentina (Ley 11.723) protege los derechos de autor de las obras literarias, científicas y artísticas, incluyendo el software. Los principales artículos que salvaguardan a ARGBroke son:  

_Artículo 1:_ Protege las obras literarias y científicas, incluyendo el software, asegurando que el código de ARGBroke esté protegido por derechos de autor. 

_Artículo 2:_ Otorga a ARGBroke derechos exclusivos sobre su software, incluyendo la reproducción, distribución y adaptación. La replicación no autorizada del código constituye una infracción de estos derechos. 

_Artículo 3:_ Permite a ARGBroke explotar económicamente su software y autorizar o prohibir su uso por terceros, garantizando una compensación económica adecuada por su trabajo. 

_Artículo 4:_ Protege los derechos morales de ARGBroke, asegurando que sea reconocido como el autor y que su código no sea alterado de manera perjudicial. 

_Artículo 5:_ Establece las infracciones y sanciones correspondientes, permitiendo a ARGBroke iniciar acciones legales contra los infractores, que pueden incluir medidas cautelares, indemnizaciones por daños y perjuicios, y sanciones penales en casos graves. 

 
Esta ley proporciona una sólida protección legal a ARGBroker permitiendo tomar acciones legales contra la replicación no autorizada de su código y asegurar sus derechos de autor, económico y morales. 

/// Salvaguardar: significa proteger y hacer valer los derechos de propiedad intelectual mediante los recursos legales disponibles.

**Comment by luchogigena** [comment]
¿ Cómo puede la ley de propiedad intelectual salvaguardar a ARGBroker si el código es replicado?  

Protección del Código  

**_Carlos, Especialista en Seguridad Informática_**:  

**_Rol:_**  

**_Detección de Infracciones:_** Carlos es responsable de implementar y monitorear sistemas de seguridad que detecten cualquier uso no autorizado del código. Esto incluye el uso de herramientas de monitoreo, auditorías de seguridad y sistemas de detección de intrusiones.  

**_Documentación de Evidencia:_** Carlos debe documentar cualquier intento o incidente de replicación no autorizada del código, recolectando evidencias como registros de acceso, capturas de pantalla y cualquier otra información relevante.  

 **_### Coordinación con el Equipo Legal:_** Carlos trabaja en estrecha colaboración con el equipo legal para proporcionar toda la información necesaria para iniciar acciones legales contra los infractores, tanto a nivel nacional como internacional.  

**_Ejemplo_**:  

Carlos,  especialista en seguridad informática de ARGBroke, detecta que otro integrante del grupo ha replicado el código para fines personales sin autorización, se pueden tomar las siguientes acciones según la Ley 11.723.  

**_Acción Legal:_** Carlos documenta el incidente y proporciona evidencia al equipo legal de ARGBroke. Con base en los artículos 1, 2, 3, 4 y 5 de la Ley 11.723, ARGBroke puede iniciar acciones legales por infracción de derechos de autor.  

**_Pena por Infracción:_**  

Artículo 5 de la Ley 11.723 establece que la infracción de los derechos de autor puede resultar en sanciones que incluyen multas y penas de prisión. Según el Código Penal de la Nación, modificado por la Ley 26.388, la pena por delitos informáticos, incluyendo la reproducción y distribución no autorizada
