### ISSUE TITLE
Etica 7: Si un integrante del grupo divulga los datos de la base de datos interna, describir como legalmente deberían accionar los demás.

### ISSUE THREAD

**Issue by Maxg8704** [Grupo-Seven-ISPC/ARGBroker-Demo-Grupo-Seven#24]

**Comment by marialis19** [comment]
7. Divulgación de Datos Internos

 - Acción legal:
     · Ley 25.326: Iniciar una acción legal por violación de la privacidad y confidencialidad de los datos, incluyendo sanciones penales y civiles.
     · Artículo 32: Sanciones penales, será reprimido con la pena de prisión de un mes a dos años.  (constatar o modificar)
     · Artículo 8 del código penal argentino (contatar o agregar)

**Comment by AnaCamilaAlmiron** [comment]
Nos enteramos que Maxi, uno de los socios de nuestra empresa, divulgo los datos de nuestra base de datos, nosotros recurrimos a la aplicación de la ley 25.362 que hace alusión a la protección de los datos personales, decreta que la pena para este integrante es de un mes a dos años de prisión, ya que revelo información de nuestro banco de base de datos, clausula que firmamos en el contrato
