### ISSUE TITLE
Etica: 8. Si otro integrante del grupo reutiliza el código para fines personales, describir como legalmente deberían accionar los demás según la Legislación de la Provincia de Córdoba y el Código Penal Argentino.

### ISSUE THREAD

**Issue by Maxg8704** [Grupo-Seven-ISPC/ARGBroker-Demo-Grupo-Seven#25]

**Comment by marialis19** [comment]
8. Reutilización de Código para Fines Personales

- Acción legal en Córdoba y Nacional:
     
     · Ley 11.72: Protección de derechos de autor, artículos 1 y 2 (ver demás articulos involucrados)
     · Código Penal argentino: Acciones penales por uso no autorizado de propiedad intelectual (constatar artículos involucrados)

**Comment by AnaCamilaAlmiron** [comment]
El articulo 307 del código penal argentino, que trata contra el orden económico, pena de 1 a 4 años al uso de información privilegiada a la que se tuvo acceso durante su actividad, se eleva de 2 a máximo 6 años cuando el uso o suministro de esa información da lugar a la obtención de un beneficio económico personal para si o para terceros.

**Comment by AnaCamilaAlmiron** [comment]
Camila, una de las socias, estuvo utilizando nuestro código para un proyecto personal, accionando según el código penal argentino le corresponde una pena de 1 a 4 años de prisión, por el uso de información privilegiada a la que tuvo acceso durante la actividad en nuestra empresa, no sabemos si lo hizo para un beneficio económico personal o para terceros, pero en ese caso la pena se eleva de 2 a un máximo de 6 años.
