### ISSUE TITLE
Etica: 9. Si otro integrante del grupo reutiliza el código para fines personales a nivel internacional, describir qué instrumento legal respalda a ARGBroker.

### ISSUE THREAD

**Issue by Maxg8704** [Grupo-Seven-ISPC/ARGBroker-Demo-Grupo-Seven#26]

**Comment by marialis19** [comment]
9. Reutilización de Código a Nivel Internacional

- Instrumento Legal:

     · Convenio de Ciberseguridad o de Budapest: Acceso Ilícito, Interferencia Ilícita (expandir qué capitulos y/o artículos)

**Comment by luchogigena** [comment]
**_Instrumento Legal: Convenio de Budapest_**

Con respecto al Convenio de Budapest sobre Ciberdelincuencia, Carlos, como responsable de la seguridad informática en ARGBroker, debería:
1.	Identificar la Infracción:  debe determinar si la reutilización no autorizada del código constituye una infracción del Convenio de Budapest sobre Ciberdelincuencia.
2.	Informar a las Autoridades Competentes: Si la infracción es de naturaleza cibernética y cae dentro del ámbito del Convenio de Budapest, Carlos debe informar a las autoridades competentes sobre el incidente y colaborar estrechamente con ellas en la investigación.
3.	Proporcionar Evidencia y Cooperar en la Investigación:  debe recopilar y proporcionar toda la evidencia relevante relacionada con la infracción y cooperar plenamente con las autoridades en la investigación del delito cibernético.
4.	Seguir los Procedimientos del Convenio:  debe asegurarse de seguir los procedimientos establecidos en el Convenio de Budapest para la cooperación internacional en la investigación y persecución de delitos cibernéticos.
5.	Actualizar las Medidas de Seguridad: Como medida preventiva,  también debe actualizar y reforzar las medidas de seguridad informática de ARGBroker para evitar futuras infracción del Convenio de Budapest y otras formas de delitos cibernéticos.
