### ISSUE TITLE
Etica: 10. Si la base de datos es adulterada de manera externa, a nivel nacional, describir qué instrumento legal respalda a ARGBroker.

### ISSUE THREAD

**Issue by Maxg8704** [Grupo-Seven-ISPC/ARGBroker-Demo-Grupo-Seven#27]

**Comment by marialis19** [comment]
10. Adulteración de Base de Datos Nacionalmente

- Instrumento Legal:

     · Ley 26.388 de Delitos Infomáticos: Protección contra adulteración de datos ( artículos 32? )
(constatar, agregar)

**Comment by AnaCamilaAlmiron** [comment]
(ley 26.388) 1 mes a 2 años al que alterare, destruyere, o inutilzare datos, documentos, programas o sist informaticos, o vendiere, distribuyere, hiciere circular o introdujere en un sist informatico cualquier programa destinado a causar daños
(ley 25326) 1 mes a 2 años al que a sabiendas e ilegitimamente, o violando sistemas de confidencialidad y seguridad de datos, accediere de cualquier forma a un banco de datos personales.
(codigo penal) al que defraudare a otro mediante cualquier tecnica de manipulacion informatica que altere el normal funcionamiento de un sist informaticoo la transmision de datos.

**Comment by AnaCamilaAlmiron** [comment]
Descubrimos que nuestra base de datos fue alterada de manera externa, para ellos recurrimos a las leyes 26.388 y 25.326, que condenan de 1 mes a 2 años de prisión al que altere, destruyere o inutilizare datos, documentos o programas informáticos, o vendiere, distribuyere o introdujere en un sistema informático cualquier programa con el fin de causar daños. También al que a sabiendas e ilegítimamente, o violando sistemas de confidencialidad y de seguridad de datos, accediere de igual forma a un banco de base de datos. Acudiendo al código penal, este pena al que defraudare a otro mediante cualquier técnica de manipulación informática al que altere el normal funcionamiento de un sistema informático o la transmisión de datos.
