### ISSUE TITLE
Etica: 11. Si los datos de la base de datos son adulterados de manera externa, a nivel internacional, describir qué instrumento legal respalda a ARGBroker.

### ISSUE THREAD

**Issue by Maxg8704** [Grupo-Seven-ISPC/ARGBroker-Demo-Grupo-Seven#28]

**Comment by marialis19** [comment]
11. Adulteración de Datos Internacionalmente
 
Instrumento legal: Convenio de Budapest sobre la ciberdelincuencia  
     · Artículo 2 Acceso Ilícito: Penaliza el acceso sin autorización a sistemas informáticos.
     · Artículo 4 Intercepción Ilícita: Sanciona la intercepción ilegal de datos informáticos.
     · Artículo 5 Interferencia en los Datos: Tipifica como delito la alteración, destrucción, supresión o deterioro de datos informáticos sin derechos.
    · Artículo 6 Interferencia en el Sistema: Penaliza el impedimento grave o la interrupción del funcionamiento de un sistema informático.

**Comment by luchogigena** [comment]
**### Instrumento Legal que respalda a ARGBroker en caso de adulteración de manera externa la base de datos.** 

### **Convenio de Budapest sobre Ciberdelincuencia:** 

Este Convenio proporciona un respaldo legal y práctico a ARGBroke para enfrentar la adulteración de datos a nivel internacional. 

Facilita la cooperación internacional para investigar y perseguir delitos informáticos. ARGBroke puede solicitar asistencia a otros países signatarios para investigar y procesar a los atacantes. 

 _-Procedimiento en caso de adulteración de datos:_ 

_Denuncia_: ARGBroke puede denunciar el incidente a las autoridades nacionales competentes. 

_Solicitud de Asistencia:_ Las autoridades argentinas pueden solicitar cooperación internacional a través del Convenio de Budapest para investigar el origen del ataque y los responsables en otros países. 

_Investigación y Persecución:_ Utilizar las disposiciones del convenio para llevar a cabo investigaciones conjuntas y, si es necesario, solicitar la extradición de los delincuentes. 

 

 

_// signatarios son los países que han acordado adherirse y cumplir con los términos de un tratado o convenio internacional._
