### ISSUE TITLE
Etica: 14. Si el cliente decide reemplazar a ARGBroker por otro proveedor, describir cómo se debe actuar de manera ética ante el cliente y los colegas.

### ISSUE THREAD

**Issue by Maxg8704** [Grupo-Seven-ISPC/ARGBroker-Demo-Grupo-Seven#31]

**Comment by Nachofferreyra** [comment]
En el supuesto de que un cliente solicite el reemplazo de ARGBroker por otro proveedor distinto, resulta necesario tener presente que el proceso debe llevarse a cabo de manera clara, objetiva, colaborativa y, sobre todo, observando el cumplimiento de las obligaciones establecidas al inicio de la relación con el cliente. En el caso de que no exista un contrato entre las partes, se deberán respetar los principios y normativas concernientes al tratamiento de la información personal, conforme a lo dispuesto en la Ley 25.326, así como los principios éticos relativos a la finalización de la relación.
Es fundamental que todas las acciones realizadas durante el proceso de cambio de proveedor se rijan por estándares éticos y profesionales. Esto implica mantener una comunicación transparente y honesta con el cliente, brindándole toda la información relevante sobre el proceso de transición, incluyendo posibles desafíos, plazos y soluciones propuestas. Además, se debe respetar la confidencialidad de la información del cliente y garantizar la seguridad y protección de sus datos en todo momento.
Durante la transición a un nuevo proveedor, es esencial mantener una comunicación abierta y transparente, con el propósito de no entorpecer la transferencia y, además, abordar aspectos relevantes tanto para el cliente como para la empresa. Esto incluye, por ejemplo, las oportunidades de mejora, el mantenimiento del estatus o nivel de servicios, colaborando en el proceso que se llevará a cabo para efectuar el traspaso al nuevo proveedor.
Asimismo, resulta necesario y prioritario mantener el orden y la protección integral de los datos, tanto personales como sensibles, que hayan sido objeto de intervención a lo largo de la relación contractual. Dichos datos deberán ser eliminados cuando hayan dejado de ser necesarios o pertinentes para los fines para los cuales fueron recolectados.

Con respecto a los colegas y colaboradores internos, es esencial fomentar un ambiente de trabajo colaborativo y respetuoso durante el proceso de cambio de proveedor. Esto implica compartir conocimientos y experiencias relevantes para facilitar la transición de manera fluida y efectiva. Asimismo, se deben reconocer y valorar las contribuciones de todos los miembros del equipo involucrados en el proceso, promoviendo un clima laboral positivo y de apoyo mutuo.
