### ISSUE TITLE
Etica: 15. Si un usuario denuncia a ARGBroker por divulgación de sus datos personales, a que legislación recurrió el mismo y como ARGBroker puede respaldarse jurídicamente.

### ISSUE THREAD

**Issue by Maxg8704** [Grupo-Seven-ISPC/ARGBroker-Demo-Grupo-Seven#32]

**Comment by Nachofferreyra** [comment]
En el caso de que un usuario presente una denuncia contra ARGBroker por la divulgación de sus datos personales, haciendo referencia a la ley 25.326, conocida como "Ley de Protección de Datos Personales", la empresa debe asegurar que cumple con las disposiciones y requisitos establecidos por dicha ley.

Para respaldar su posición frente a dicha denuncia, ARGBroker debe verificar el cumplimiento normativo, garantizando que se obtuvo el consentimiento del titular de los datos para el tratamiento de su información, que se implementaron medidas de seguridad adecuadas para proteger los datos personales y que se respetaron los derechos de los titulares de los datos.

Además, es fundamental que la empresa mantenga una documentación exhaustiva de todas las actividades relacionadas con el tratamiento de datos personales, incluyendo los consentimientos obtenidos, las medidas de seguridad implementadas y cualquier otra acción tomada al respecto.

Asimismo, ARGBroker debe contar con políticas y procedimientos internos transparentes que regulen el manejo de los datos, así como brindar capacitación adecuada en materia de protección de información personal al personal interno involucrado en dichos procesos.

**Comment by GonzalezEzequiel** [comment]
Cumplimiento de la Ley N° 25.326:

Consentimiento Informado: Asegurarse de que los datos personales fueron recolectados con el consentimiento explícito del usuario.

Derechos de Acceso y Rectificación: Garantizar que el usuario tenía acceso a sus datos y la posibilidad de rectificarlos si fuera necesario.

Principio de Calidad de Datos: Verificar que los datos sean adecuados, pertinentes y no excesivos en relación con el ámbito y finalidad para los que se recolectaron.

Seguridad de los Datos: Implementar medidas de seguridad adecuadas para proteger los datos personales contra la pérdida, acceso no autorizado, alteración o divulgación.
