### ISSUE TITLE
Programación I: 1. Identificar las clases del sistema, atributos y métodos.

### ISSUE THREAD

**Issue by Maxg8704** [Grupo-Seven-ISPC/ARGBroker-Demo-Grupo-Seven#7]

**Comment by GonzalezEzequiel** [comment]
Clases Principales:
Broker
Cliente
Cuenta
Transacción
Instrumento
Orden
Mercado

Descripción de Clases, Atributos y Métodos
1. Broker
Atributos:

nombre: Nombre del broker.
clientes: Lista de clientes asociados al broker.
mercados: Lista de mercados donde opera el broker.
Métodos:

agregar_cliente(cliente): Agrega un nuevo cliente.
remover_cliente(cliente): Remueve un cliente.
realizar_transaccion(transaccion): Realiza una transacción para un cliente.
consultar_mercados(): Devuelve información sobre los mercados disponibles.
actualizar_mercado(mercado): Actualiza la información de un mercado.
2. Cliente
Atributos:

id: Identificador único del cliente.
nombre: Nombre del cliente.
cuentas: Lista de cuentas del cliente.
Métodos:

abrir_cuenta(tipo): Abre una nueva cuenta del tipo especificado.
cerrar_cuenta(cuenta): Cierra una cuenta específica.
consultar_cuentas(): Devuelve información sobre todas las cuentas del cliente.
3. Cuenta
Atributos:

numero: Número de cuenta.
saldo: Saldo disponible en la cuenta.
tipo: Tipo de cuenta (por ejemplo, ahorro, inversión).
transacciones: Lista de transacciones asociadas con la cuenta.
Métodos:

depositar(cantidad): Deposita una cantidad de dinero en la cuenta.
retirar(cantidad): Retira una cantidad de dinero de la cuenta.
consultar_saldo(): Devuelve el saldo actual.
agregar_transaccion(transaccion): Agrega una transacción a la cuenta.
4. Transacción
Atributos:

id: Identificador único de la transacción.
tipo: Tipo de transacción (compra, venta, depósito, retiro).
monto: Monto de la transacción.
fecha: Fecha de la transacción.
Métodos:

ejecutar(): Ejecuta la transacción.
revertir(): Revierte la transacción.
5. Instrumento
Atributos:

ticker: Símbolo del instrumento financiero.
nombre: Nombre del instrumento.
precio_actual: Precio actual del instrumento.
Métodos:

actualizar_precio(precio): Actualiza el precio del instrumento.
consultar_precio(): Devuelve el precio actual del instrumento.
6. Orden
Atributos:

id: Identificador único de la orden.
tipo: Tipo de orden (compra, venta).
instrumento: Instrumento financiero asociado a la orden.
cantidad: Cantidad de instrumentos a comprar o vender.
precio_limite: Precio límite para la orden.
estado: Estado de la orden (pendiente, completada, cancelada).
Métodos:

ejecutar_orden(): Ejecuta la orden.
cancelar_orden(): Cancela la orden.
consultar_estado(): Devuelve el estado actual de la orden.
7. Mercado
Atributos:

nombre: Nombre del mercado.
instrumentos: Lista de instrumentos disponibles en el mercado.
indice: Valor del índice del mercado.
Métodos:

agregar_instrumento(instrumento): Agrega un nuevo instrumento al mercado.
remover_instrumento(instrumento): Remueve un instrumento del mercado.
consultar_instrumentos(): Devuelve la lista de instrumentos disponibles.
